export const ActionTypes = {
    ADD_FAVORITE : "ADD_FAVORITE",
    REMOVE_FAVORITE : "REMOVE_FAVORITE",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    AJUST_QUANTITY : "AJUST_QUANTITY",
    APPLY_FILTER : "APPLY_FILTER",
}